import SwiftUI

struct CertPickerView: View {
    private let certs = CertCatalog.all
    private let progressManager = ProgressManager.shared
    @State private var showBackup = false

    private let columns = [
        GridItem(.adaptive(minimum: 280, maximum: 400), spacing: 20)
    ]

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 32) {

                    // Expiration Warning Banner
                    if progressManager.isExpiringSoon {
                        Button { showBackup = true } label: {
                            HStack(spacing: 10) {
                                Image(systemName: "exclamationmark.triangle.fill")
                                    .foregroundStyle(.white)
                                VStack(alignment: .leading, spacing: 2) {
                                    Text("App expires in \(progressManager.daysRemaining) day\(progressManager.daysRemaining == 1 ? "" : "s")")
                                        .font(.subheadline)
                                        .fontWeight(.semibold)
                                        .foregroundStyle(.white)
                                    Text("Tap to back up your study progress")
                                        .font(.caption)
                                        .foregroundStyle(.white.opacity(0.85))
                                }
                                Spacer()
                                Image(systemName: "chevron.right")
                                    .foregroundStyle(.white.opacity(0.7))
                            }
                            .padding()
                            .background(
                                LinearGradient(
                                    colors: [.red, .orange],
                                    startPoint: .leading,
                                    endPoint: .trailing
                                )
                            )
                            .clipShape(RoundedRectangle(cornerRadius: 12))
                            .padding(.horizontal, 20)
                        }
                        .buttonStyle(.plain)
                    }

                    // Header
                    VStack(spacing: 8) {
                        Image(systemName: "graduationcap.fill")
                            .font(.system(size: 48))
                            .foregroundStyle(
                                LinearGradient(
                                    colors: [.indigo, .teal],
                                    startPoint: .topLeading,
                                    endPoint: .bottomTrailing
                                )
                            )

                        Text("Cert Study Hub")
                            .font(.largeTitle)
                            .fontWeight(.bold)

                        Text("Choose a certification to study")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                    .padding(.top, 24)

                    // Cert Cards
                    LazyVGrid(columns: columns, spacing: 20) {
                        ForEach(certs) { cert in
                            NavigationLink(value: cert.id) {
                                CertCard(cert: cert)
                            }
                            .buttonStyle(.plain)
                        }
                    }
                    .padding(.horizontal, 20)

                    // AI Disclaimer
                    HStack(spacing: 6) {
                        Image(systemName: "sparkles")
                            .font(.caption2)
                        Text("Some content in this app was generated by AI and may contain inaccuracies.")
                            .font(.caption2)
                    }
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 32)
                    .padding(.bottom, 24)
                }
            }
            .background(PlatformColor.groupedBackground)
            .navigationDestination(for: String.self) { certId in
                if let cert = certs.first(where: { $0.id == certId }) {
                    CertHomeView(certConfig: cert)
                }
            }
            .toolbar {
                ToolbarItem(placement: .automatic) {
                    Button { showBackup = true } label: {
                        Image(systemName: "arrow.up.arrow.down.circle")
                    }
                }
            }
            .sheet(isPresented: $showBackup) {
                ProgressExportView()
            }
        }
    }
}

// MARK: - Cert Card

struct CertCard: View {
    let cert: CertConfig

    var body: some View {
        VStack(spacing: 16) {
            // Icon
            ZStack {
                Circle()
                    .fill(
                        LinearGradient(
                            colors: [cert.primaryColor, cert.secondaryColor],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .frame(width: 64, height: 64)

                Image(systemName: cert.icon)
                    .font(.system(size: 28))
                    .foregroundStyle(.white)
            }

            // Title
            Text(cert.name)
                .font(.headline)
                .fontWeight(.bold)
                .multilineTextAlignment(.center)
                .foregroundStyle(.primary)

            // Subtitle for bonus topics
            if let subtitle = cert.subtitle {
                HStack(spacing: 4) {
                    Image(systemName: "star.fill")
                        .font(.system(size: 9))
                    Text(subtitle)
                        .font(.caption2)
                }
                .foregroundStyle(.orange)
                .padding(.horizontal, 10)
                .padding(.vertical, 3)
                .background(
                    Capsule()
                        .fill(.orange.opacity(0.12))
                )
            }

            // Stats
            HStack(spacing: 16) {
                HStack(spacing: 4) {
                    Image(systemName: "questionmark.circle.fill")
                        .font(.caption)
                        .foregroundStyle(cert.primaryColor)
                    Text("\(cert.questionCount) questions")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                HStack(spacing: 4) {
                    Image(systemName: "book.fill")
                        .font(.caption)
                        .foregroundStyle(cert.primaryColor)
                    Text("\(cert.topicCount) topics")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            // Passing score badge
            if !cert.isBonusTopic {
                Text("Passing: \(cert.passingScore)%")
                    .font(.caption2)
                    .fontWeight(.semibold)
                    .foregroundStyle(cert.primaryColor)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 4)
                    .background(
                        Capsule()
                            .fill(cert.primaryColor.opacity(0.1))
                    )
            }
        }
        .padding(24)
        .frame(maxWidth: .infinity)
        .background(PlatformColor.secondaryBackground)
        .clipShape(RoundedRectangle(cornerRadius: 16))
        .overlay(
            RoundedRectangle(cornerRadius: 16)
                .stroke(PlatformColor.separator, lineWidth: 0.5)
        )
        .shadow(color: .black.opacity(0.05), radius: 8, y: 4)
    }
}
